### ISSUE TITLE
there was a problem, because the animation pictures change of colors for upload from discord and every website.

### ISSUE THREAD

**Issue by Misterkiwi500** [ArtVentureX/comfyui-animatediff#1]
I have already generated an animation image from here. Colab looks good but when I upload it to Discord the colors actually look blurry, which means the colors from this image change. Question is, can you fix it because of random colors? Thanks

example animation pic: 
![0858cf98-df49-4768-a82d-a12de5c7b02d](https://github.com/ArtVentureX/comfyui-animatediff/assets/53793601/ca3ac8cb-00b4-4ecb-b6fe-72b50f45e7d9)

**Comment by Misterkiwi500** [comment]
I'm sorry! this is an animation furry. :sweat_smile:

**Comment by artventuredev** [comment]
> I have already generated an animation image from here. Colab looks good but when I upload it to Discord the colors actually look blurry, which means the colors from this image change. Question is, can you fix it because of random colors? Thanks

If the colors appear blurry after uploading the image to Discord, it could be due to compression by Discord itself. 

I've also noticed washed/greyed out colors when generating images with certain models. Since I'm porting the extension from the original repository, there's limited control over this issue. However, I'll keep an eye out for any potential fixes or workarounds.
