### ISSUE TITLE
MP4 format does not appear in the animatediff combine node (DEPRECATED)

### ISSUE THREAD

**Issue by aestendrela** [ArtVentureX/comfyui-animatediff#45]
I would like to know how I can make the result of animatediff to be saved in MP4. Currently I only have the option to save it as GIF and/or wep3.

Thank you very much for your help.

**Comment by artventuredev** [comment]
Could you please provide a screenshot of your workflow? I suspect that you might have multiple AnimateDiff extensions installed and could be using the combine node from a different extension.

You can also try other video support nodes from [this repo (Kosinkadink/ComfyUI-VideoHelperSuite)](https://github.com/Kosinkadink/ComfyUI-VideoHelperSuite), including video loading, saving, frame manipulation...

<img width="677" alt="image" src="https://github.com/ArtVentureX/comfyui-animatediff/assets/133728487/e032de12-3856-444e-b7ac-bf6704d44f2e">

**Comment by aestendrela** [comment]
I have already solved it! 
Thank you very much! That's exactly what was happening to me!

**Comment by vicitooo** [comment]
I can't seem to solve it. I have installed [this repo (Kosinkadink/ComfyUI-VideoHelperSuite)](https://github.com/Kosinkadink/ComfyUI-VideoHelperSuite) as well as ffmpeg and still don't see the mp4 option. Also my node says deprecated. Maybe that's why? 
![deprecated](https://github.com/ArtVentureX/comfyui-animatediff/assets/41148215/93c2dac8-4014-4662-8c19-523aef64e7dd)
